name: Update YouTube Cards
on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update YouTube cards
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCf2AdxyhFLGE1DKcTnyefSw  # Replace with your YouTube Channel ID
          comment_tag_name: YOUTUBE-CARDS
          max_videos: 4
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated YouTube videos" || exit 0
          git push
